name: knowabunga_app
description: Flutter showcase app for Knowabunga 2023 talk.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/activities/
    - assets/images/discussion_panels/
    - assets/images/food_and_drinks/
    - assets/images/talks/
    - assets/gifs/
